name: Monday Motivation

on:
  schedule:
    - cron: "0 6 * * 1"   # Every Monday at 7 AM Nigeria time (UTC+1 → 6 UTC)
  workflow_dispatch:

jobs:
  send-quote:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Python script
        run: python main.py
        env:
          MY_EMAIL: ${{ secrets.MY_EMAIL }}
          MY_PASSWORD: ${{ secrets.MY_PASSWORD }}
